# Generated by Django 4.2.4 on 2023-08-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_product_details_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_discount',
            field=models.IntegerField(null=True),
        ),
    ]
