# Generated by Django 4.2.4 on 2023-08-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
    ]
